DELETE FROM INGREDIENT;
INSERT INTO INGREDIENT VALUES(1,'Ingredient-1');
INSERT INTO INGREDIENT VALUES(2,'Ingredient-2');
INSERT INTO INGREDIENT VALUES(3,'Ingredient-3');
INSERT INTO INGREDIENT VALUES(4,'Ingredient-4');
INSERT INTO INGREDIENT VALUES(5,'Ingredient-5');
INSERT INTO INGREDIENT VALUES(6,'Ingredient-6');
INSERT INTO INGREDIENT VALUES(7,'Ingredient-7');
INSERT INTO INGREDIENT VALUES(8,'Ingredient-8');
INSERT INTO INGREDIENT VALUES(9,'Ingredient-9');
INSERT INTO INGREDIENT VALUES(10,'Ingredient-10');

DELETE FROM RECIPE;
INSERT INTO RECIPE VALUES(1,'Recipe-1',4,'instructions-1 keyword1 keyword2 keyword3 keyword4  keyword5',FALSE);
INSERT INTO RECIPE VALUES(2,'Recipe-2',2,'instructions-2 keyword2 keyword3 keyword4',TRUE);
INSERT INTO RECIPE VALUES(3,'Recipe-3',7,'instructions-3 keyword7 keyword1',FALSE);

DELETE FROM RECIPE_INGREDIENT;
INSERT INTO RECIPE_INGREDIENT VALUES(1,1);
INSERT INTO RECIPE_INGREDIENT VALUES(4,1);
INSERT INTO RECIPE_INGREDIENT VALUES(8,1);
INSERT INTO RECIPE_INGREDIENT VALUES(6,1);
INSERT INTO RECIPE_INGREDIENT VALUES(4,2);
INSERT INTO RECIPE_INGREDIENT VALUES(3,2);
INSERT INTO RECIPE_INGREDIENT VALUES(9,2);
INSERT INTO RECIPE_INGREDIENT VALUES(10,3);
INSERT INTO RECIPE_INGREDIENT VALUES(9,3);
INSERT INTO RECIPE_INGREDIENT VALUES(7,3);
INSERT INTO RECIPE_INGREDIENT VALUES(1,3);




